### ISSUE TITLE
Outside Filament - input value is null when the form is submitted 

### ISSUE THREAD

**Issue by hanifw** [ysfkaya/filament-phone-input#28] opened 2023-12-08 08:43 UTC
I tried using this for outside filament (livewire), displaying the input with country selection, and most of the options, etc work well. 

However, when the form is submitted, the input value is null and does not pass laravel required validation.

**Comment by ysfkaya** [comment] 2023-12-09 15:01
I tested it and it works well. I'm not sure I understand you.

I used the following case;

```php
<?php

namespace App\Livewire;

use Filament\Forms\Concerns\InteractsWithForms;
use Filament\Forms\Contracts\HasForms;
use Filament\Forms\Form;
use Livewire\Component;
use Ysfkaya\FilamentPhoneInput\Forms\PhoneInput;

class Test extends Component implements HasForms
{
    use InteractsWithForms;

    public ?array $data = [];

    public function mount()
    {
        // You need to fill the form in mount method.
        $this->form->fill();
    }

    public function form(Form $form): Form
    {
        return $form->schema([
            PhoneInput::make('phone')->required()
        ])->statePath('data');
    }

    public function create()
    {
        $state = $this->form->getState();

        dd($state);
    }

    public function render()
    {
        return view('livewire.test');
    }
}
```

The required validation is not passing if value is not set. Also the input value is not getting null anytime. Try this way.

**Comment by hanifw** [comment] 2023-12-11 00:28
I tried the same but got this, not sure what went wrong.

<img width="755" alt="image" src="https://github.com/ysfkaya/filament-phone-input/assets/229192/f4907b19-0e06-4b3c-bb24-ce46a4bf5fe8">

<?php

namespace App\Livewire;

use App\Models\User;
use Livewire\Component;
use Filament\Forms\Form;
use Filament\Actions\Action;
use Illuminate\Support\Facades\URL;
use Filament\Forms\Components\Select;
use Filament\Forms\Contracts\HasForms;
use Illuminate\Auth\Events\Registered;
use Filament\Forms\Components\TextInput;
use App\Services\ServiceOnboardingDetail;
use Filament\Actions\Contracts\HasActions;
use Filament\Forms\Concerns\InteractsWithForms;
use Filament\Actions\Concerns\InteractsWithActions;
use Ysfkaya\FilamentPhoneInput\Forms\PhoneInput;
use Rawilk\FilamentPasswordInput\Password;

class OnboardingUser extends Component implements HasForms, HasActions
{
    use InteractsWithForms;
    use InteractsWithActions;

    public ?array $data = [];

    public function mount()
    {
        // You need to fill the form in mount method.
        $this->form->fill();
    }

    public function form(Form $form): Form
    {
        return $form
            ->schema([
                TextInput::make('name')
                    ->label('Full name')
                    ->placeholder('Your full name')
                    ->rules('required'),
                TextInput::make('email')
                    ->placeholder('yourname@yourcompany.com')
                    ->email()
                    ->rules(['email', 'required', 'unique:users,email']),
                PhoneInput::make('phone')->label('Mobile number')
                    ->rules('required'),
                Password::make('password')
                    ->label('Password')
                    ->inlineSuffix()
                    ->copyable()
                    ->rules('required','min:8'),                
            ])->statePath('data');
    }

    // public function submitAction(): Action
    // {
    //     return Action::make('Next Step')
    //         ->submit('create');
    // }

    public function create()
    {
        $state = $this->form->getState();

        dd($state);
        exit;

        $personalForm = $this->form->getState();

        $user = ServiceOnboardingDetail::createUser($personalForm);
        if ($user) {
            event(new Registered($user));
            return redirect()->route('verification.send.user.get', ['user' => $user]);
        } else {
            // Reinitialize the form to clear its data.
            $this->form->fill();
            //? later -> kena guna session->flash untuk livewire , withErrors Tak Jadi , If im not mistaken
            return redirect()->back()->withInput()->withErrors(['message' => 'User creation failed']);
        }
    }

    public function render()
    {
        return view('livewire.onboarding.onboarding-user');
    }
}

**Comment by ysfkaya** [comment] 2023-12-11 06:28
Your phone number is not valid. You can check here

https://intl-tel-input.com/examples/validation.html

If I remember correctly, the value does not affect to the `state` of component if it is not a valid phone number. Have you tried another number?

**Comment by hanifw** [comment] 2023-12-11 06:31
It's a valid number because it is my phone number.

**Comment by ysfkaya** [comment] 2023-12-11 09:21
I just realized it's the Malaysian flag, my bad. But it still seems to work when I test it. I don't think the problem is caused by the plugin.

![Screenshot 2023-12-11 at 12 19 01](https://github.com/ysfkaya/filament-phone-input/assets/16710972/552acb66-4ede-4bc5-a79d-3e73b8011a5e)

**Comment by hanifw** [comment] 2023-12-13 04:03
Have you tried on the latest filament v3?

**Comment by ysfkaya** [comment] 2023-12-17 22:13
I am closing this issue as there is no more reaction. If you have any questions, you can post them in the discussion section.

**Closed** 2023-12-17 22:13 UTC

**Comment by sezohessen** [comment] 2024-07-28 11:40
I am getting the same validation error even if the phone number is valid
```
                        PhoneInput::make('mobile')
                            ->label('Phone')
                            ->required(),
```

**Comment by ysfkaya** [comment] 2024-07-28 11:53
> I am getting the same validation error even if the phone number is valid
> 
> ```
>                         PhoneInput::make('mobile')
>                             ->label('Phone')
>                             ->required(),
> ```

Did you `fill` the form in the `mount` method?

```php
public function mount(): void
{
    $this->form->fill();
}
```

**Comment by sezohessen** [comment] 2024-07-28 12:51
Thank you , Solved
